// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCuQ60QvfSefv5-BCzkTY0-xBfhj_qzzA',
    appId: '1:668827673700:web:2c41573524a9d2646f2b71',
    messagingSenderId: '668827673700',
    projectId: 'chathub-37058',
    authDomain: 'chathub-37058.firebaseapp.com',
    storageBucket: 'chathub-37058.appspot.com',
    measurementId: 'G-BWHWBR4TEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FQdY2oljqCiaoIsrIH70lalRgoSDt0k',
    appId: '1:668827673700:android:20808926486bc44c6f2b71',
    messagingSenderId: '668827673700',
    projectId: 'chathub-37058',
    storageBucket: 'chathub-37058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_OftPZNvIn1sPTaoYwvAjUz_MWJSN6E',
    appId: '1:668827673700:ios:07db973d0865f4ff6f2b71',
    messagingSenderId: '668827673700',
    projectId: 'chathub-37058',
    storageBucket: 'chathub-37058.appspot.com',
    iosBundleId: 'com.example.chathub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_OftPZNvIn1sPTaoYwvAjUz_MWJSN6E',
    appId: '1:668827673700:ios:f9085124e9d6d4e36f2b71',
    messagingSenderId: '668827673700',
    projectId: 'chathub-37058',
    storageBucket: 'chathub-37058.appspot.com',
    iosBundleId: 'com.example.chathub.RunnerTests',
  );
}
